# Generated by Django 6.0.3 on 2026-04-11 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выдан/Завершен')),
                ('cashback_awarded', models.BooleanField(default=False, editable=False)),
                ('use_bonuses', models.BooleanField(default=False, verbose_name='Списать бонусы?')),
                ('bonuses_spent', models.PositiveIntegerField(default=0, verbose_name='Списано бонусов')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес (пусто = самовывоз)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message', models.TextField(verbose_name='Сообщение клиента')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Ответ администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Вопрос решен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='order.order', verbose_name='К какому заказу')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Earn', 'Начисление'), ('Spend', 'Списание'), ('Refund', 'Возврат'), ('Gift', 'Подарок от админа')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.bonuswallet')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to='order.order', verbose_name='Связанный заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за 1 шт.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.product', verbose_name='Товар')),
            ],
        ),
    ]
